package droolsexample

import com.test.Test.Message;
import com.test.Test.Message2;
import com.micro.services.search.api.request.SearchServiceRequest;
import com.micro.services.search.api.response.SearchServiceResponse;

global java.util.List list

rule "Hello World"
    dialect "java"
    when
        m : Message( status == Message.HELLO, message : message )
        m2 : Message2()
    then
        System.out.println( message );
        modify ( m ) { setMessage( "Goodbyte cruel world" ),
                       setStatus( Message.GOODBYE ) };
        modify(m2){
            setName("New name ")
        }               ;
//    modify ( m ) { message = "Goodbye cruel world",
//                   status = Message.GOODBYE };
end



rule "RedirectFlower"
    dialect "java"
    when
        req : SearchServiceRequest( q == "flowers" )
        res : SearchServiceResponse()
    then
        System.out.println( req );
        modify (res ) { setRedirect( "http://abc.com/flowers-cat/roses" ) };

end

